# Read the Docs configuration file for RheoJAX
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    # Pre-install commands (if needed for system dependencies)
    pre_install:
      # Ensure pip is up to date
      - python -m pip install --upgrade pip setuptools wheel

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  # Fail on warnings to catch broken links and references
  fail_on_warning: false

# PDF/ePub disabled: 161-file LaTeX compilation exceeds RTD build timeout.
# Generate locally with: make latexpdf (in docs/)
formats: []

# Python configuration
python:
  install:
    # Install the project package in editable mode
    # This ensures autodoc can import the package modules
    - method: pip
      path: .
      extra_requirements:
        - io
    # Install documentation-specific dependencies
    - requirements: docs/requirements-docs.txt
